[theme]
primaryColor = "#00619a"        # This color will apply to progress bars (green in this case)
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"
[server]
runOnSave = true
